on:
  push:
    branches:    
      - master

jobs:
  deploy:
    name: FTP Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Cleanup
      run:  |
        rm .jshintrc
        rm -rf .git
        rm -rf .github
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
        FTP_USERNAME: ${{ secrets.FTP_USER }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
