on: [push]

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy Website on hosting
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: ${{ secrets.HOSTING_USER }} 
          server: ${{ secrets.HOSTING_IP }} 
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: './*'
          remote_path: ${{ secrets.HOSTING_PATH }} 
          args: '-o ConnectTimeout=5'
